export const UPDATE_LOGGED_IN_STATUS = 'UPDATE_LOGGED_IN_STATUS';
export const USER_SEARCHED_WORD = 'USER_SEARCHED_WORD';
export const USER_FILTERED_CHECKED = 'USER_FILTERED_CHECKED';
export const SET_CURRENT_SELECTED_FILTER = 'SET_CURRENT_SELECTED_FILTER';
export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER';

// user 
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
